<?php
    get_header();
    get_template_part("/partials/front-page/banner");
    get_template_part("/partials/front-page/middle1");
    get_template_part("/partials/front-page/main");
    get_template_part("/partials/front-page/bottom1");
    get_template_part("/partials/front-page/bottom2");
    get_template_part("/partials/front-page/bottom3");
    get_template_part("/partials/front-page/bottom4");
    get_template_part("/partials/front-page/bottom5");
    get_template_part("/partials/front-page/bottom6");
    get_footer();
?>